In [1]:
import pandas as pd
import numpy as np
from openpyxl import load_workbook

In [2]:
df1 = pd.read_excel('DataProperty.xlsx', sheet_name='Bogor')
df2 = pd.read_excel('DataProperty.xlsx', sheet_name='Lampung - Sumatera selatan')
df3 = pd.read_excel('DataProperty.xlsx', sheet_name='Semarang')
df4 = pd.read_excel('DataProperty.xlsx', sheet_name='Kalimantan (All)')
df5 = pd.read_excel('DataProperty.xlsx', sheet_name='Depok')
df6 = pd.read_excel('DataProperty.xlsx', sheet_name='Tangerang')
df7 = pd.read_excel('DataProperty.xlsx', sheet_name='Jakarta')
df8 = pd.read_excel('DataProperty.xlsx', sheet_name='Padang - Palembang')
df9 = pd.read_excel('DataProperty.xlsx', sheet_name='Bekasi')
df10 = pd.read_excel('DataProperty.xlsx', sheet_name='Bandung')
df11 = pd.read_excel('DataProperty.xlsx', sheet_name='Medan')
df12 = pd.read_excel('DataProperty.xlsx', sheet_name='Surabaya')
df13 = pd.read_excel('DataProperty.xlsx', sheet_name='Bali')
df14 = pd.read_excel('DataProperty.xlsx', sheet_name='Yogyakarta')
df15 = pd.read_excel('DataProperty.xlsx', sheet_name='Sulawesi(All)')

In [3]:
combined_df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12 ,df13, df14, df15], ignore_index=True)

In [4]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3066 entries, 0 to 3065
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Created_at   3066 non-null   object
 1   LT(M2)       3066 non-null   float64
 2   LB(M2)       3065 non-null   float64
 3   KT           3064 non-null   object
 4   KM           3062 non-null   object
 5   Garasi       2014 non-null   object
 6   Carport      2511 non-null   object
 7   Lokasi       3066 non-null   object
 8   Sertifikat   3057 non-null   object
 9   Listrik      2842 non-null   object
 10  Hadap        1400 non-null   object
 11  Harga        3064 non-null   object
 12  URL          3063 non-null   object
 13  Deskripsi    3041 non-null   object
 14  Unnamed: 14  6 non-null      object
dtypes: float64(2), object(13)
memory usage: 359.4+ KB

In [5]:
combined_df.describe()

            LT(M2)       LB(M2)
count  3066.000000  3065.000000
mean    190.795280   160.478564
std     259.853244   180.928074
min       7.000000     7.000000
25%      81.000000    60.000000
50%     119.000000   100.000000
75%     200.000000   198.000000
max    5050.000000  2875.000000

In [6]:
combined_df.head()

,Created_at,LT(M2),LB(M2),KT,KM,Garasi,Carport,Lokasi,Sertifikat,Listrik,Hadap,Harga,URL,Deskripsi,Unnamed: 14
0,2021-03-12 00:00:00,75.0,38.0,2,1,1,1,Bojonggede,SHM,1300,Barat,692550000,https://rumahdijual.com/bekasi/10799791-rumah-...,"Dekat tol jati warna, dekat sutle busway, deka...",NaN
1,2021-06-12 00:00:00,60.0,40.0,1,1,0,1,Babakan Madang,SHM,2200,NaN,811400000,https://www.rumah123.com/perumahan-baru/proper...,Destinasi menarik di kawasan Babakan Madang; G...,NaN
2,2021-06-12 00:00:00,60.0,50.0,2,2,0,1,Babakan Madang,SHM,2200,NaN,900500000,https://www.rumah123.com/perumahan-baru/proper...,Destinasi menarik di kawasan Babakan Madang; G...,NaN
3,2021-06-12 00:00:00,60.0,70.0,3,2,0,1,Babakan Madang,SHM,2200,NaN,1001900000,https://www.rumah123.com/perumahan-baru/proper...,Destinasi menarik di kawasan Babakan Madang; G...,NaN
4,2021-06-12 00:00:00,90.0,60.0,3,2,0,2,Babakan Madang,SHM,2200,NaN,1200800000,https://www.rumah123.com/perumahan-baru/proper...,Destinasi menarik di kawasan Babakan Madang; G...,NaN

In [7]:
combined_df.tail()

,Created_at,LT(M2),LB(M2),KT,KM,Garasi,Carport,Lokasi,Sertifikat,Listrik,Hadap,Harga,URL,Deskripsi,Unnamed: 14
3061,19-09-2023,1030.0,467.0,2,1,0,1,"Malalayang, Manado",SHM,-,Timur,230000000000,https://www99co/id/properti/rumah-dijual-2mily...,*RUMAH DIJUAL MELALUI LELANG !!!*\n\nObjek : T...,NaN
3062,18-09-2023,96.0,96.0,2,1,0,1,"Tanjung Bunga, Makassar, Sulawesi Selatan",SHM,3500,-,67500000000,https://wwwrumahcom/listing-properti/dijual-ru...,"Dijual rumah siap huni di perumahan amarylis, ...",NaN
3063,17-09-2023,115.0,45.0,2,1,0,1,"Palu Selatan, Palu, Sulawesi Tengah",SHM,1300,-,34800000000,https://wwwrumahcom/listing-properti/dijual-di...,Jual Cepat Rumah bagus dan strategis Jl Banten...,NaN
3064,14-09-2023,102.0,72.0,2,1,0,1,"Puuwatu, Kendari Sulawesi Tenggara",HGB,900,Utara,17500000000,https://www99co/id/properti/rumah-dijual-175jt...,PERUMAHAN AFIKA LAND & AFIKA RESIDENCE TIPE 36...,NaN
3065,17-07-2023,127.0,72.0,2,1,0,1,"Mamuju, Sulawesi Barat",SHM,2200,-,60000000000,https://wwwrumah123com/properti/mamuju/hos1424...,"Di jual rumah cantik di kota mamuju sulbar, de...",NaN

In [8]:
combined_df.replace("-", np.nan, inplace = True)
combined_df.head(5)

,Created_at,LT(M2),LB(M2),KT,KM,Garasi,Carport,Lokasi,Sertifikat,Listrik,Hadap,Harga,URL,Deskripsi,Unnamed: 14
0,2021-03-12 00:00:00,75.0,38.0,2.0,1.0,1.0,1.0,Bojonggede,SHM,1300,Barat,692550000,https://rumahdijual.com/bekasi/10799791-rumah-...,"Dekat tol jati warna, dekat sutle busway, deka...",NaN
1,2021-06-12 00:00:00,60.0,40.0,1.0,1.0,0.0,1.0,Babakan Madang,SHM,2200,NaN,811400000,https://www.rumah123.com/perumahan-baru/proper...,Destinasi menarik di kawasan Babakan Madang; G...,NaN
2,2021-06-12 00:00:00,60.0,50.0,2.0,2.0,0.0,1.0,Babakan Madang,SHM,2200,NaN,900500000,https://www.rumah123.com/perumahan-baru/proper...,Destinasi menarik di kawasan Babakan Madang; G...,NaN
3,2021-06-12 00:00:00,60.0,70.0,3.0,2.0,0.0,1.0,Babakan Madang,SHM,2200,NaN,1001900000,https://www.rumah123.com/perumahan-baru/proper...,Destinasi menarik di kawasan Babakan Madang; G...,NaN
4,2021-06-12 00:00:00,90.0,60.0,3.0,2.0,0.0,2.0,Babakan Madang,SHM,2200,NaN,1200800000,https://www.rumah123.com/perumahan-baru/proper...,Destinasi menarik di kawasan Babakan Madang; G...,NaN

In [9]:
combined_df.tail(5)

,Created_at,LT(M2),LB(M2),KT,KM,Garasi,Carport,Lokasi,Sertifikat,Listrik,Hadap,Harga,URL,Deskripsi,Unnamed: 14
3061,19-09-2023,1030.0,467.0,2.0,1.0,0.0,1.0,"Malalayang, Manado",SHM,NaN,Timur,230000000000,https://www99co/id/properti/rumah-dijual-2mily...,*RUMAH DIJUAL MELALUI LELANG !!!*\n\nObjek : T...,NaN
3062,18-09-2023,96.0,96.0,2.0,1.0,0.0,1.0,"Tanjung Bunga, Makassar, Sulawesi Selatan",SHM,3500,NaN,67500000000,https://wwwrumahcom/listing-properti/dijual-ru...,"Dijual rumah siap huni di perumahan amarylis, ...",NaN
3063,17-09-2023,115.0,45.0,2.0,1.0,0.0,1.0,"Palu Selatan, Palu, Sulawesi Tengah",SHM,1300,NaN,34800000000,https://wwwrumahcom/listing-properti/dijual-di...,Jual Cepat Rumah bagus dan strategis Jl Banten...,NaN
3064,14-09-2023,102.0,72.0,2.0,1.0,0.0,1.0,"Puuwatu, Kendari Sulawesi Tenggara",HGB,900,Utara,17500000000,https://www99co/id/properti/rumah-dijual-175jt...,PERUMAHAN AFIKA LAND & AFIKA RESIDENCE TIPE 36...,NaN
3065,17-07-2023,127.0,72.0,2.0,1.0,0.0,1.0,"Mamuju, Sulawesi Barat",SHM,2200,NaN,60000000000,https://wwwrumah123com/properti/mamuju/hos1424...,"Di jual rumah cantik di kota mamuju sulbar, de...",NaN

In [10]:
missing_data = combined_df.isnull()
missing_data.head(500)

,Created_at,LT(M2),LB(M2),KT,KM,Garasi,Carport,Lokasi,Sertifikat,Listrik,Hadap,Harga,URL,Deskripsi,Unnamed: 14
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
496,False,False,False,False,False,True,True,False,False,False,True,False,False,False,True
497,False,False,False,False,False,True,True,False,False,False,True,False,False,False,True
498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
499,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True

In [11]:
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

Created_at
False    3066
Name: Created_at, dtype: int64

LT(M2)
False    3066
Name: LT(M2), dtype: int64

LB(M2)
False    3065
True        1
Name: LB(M2), dtype: int64

KT
False    3060
True        6
Name: KT, dtype: int64

KM
False    3061
True        5
Name: KM, dtype: int64

Garasi
False    1955
True     1111
Name: Garasi, dtype: int64

Carport
False    2494
True      572
Name: Carport, dtype: int64

Lokasi
False    3066
Name: Lokasi, dtype: int64

Sertifikat
False    3055
True       11
Name: Sertifikat, dtype: int64

Listrik
False    2823
True      243
Name: Listrik, dtype: int64

Hadap
True     1749
False    1317
Name: Hadap, dtype: int64

Harga
False    3064
True        2
Name: Harga, dtype: int64

URL
False    3063
True        3
Name: URL, dtype: int64

Deskripsi
False    3040
True       26
Name: Deskripsi, dtype: int64

Unnamed: 14
True     3060
False       6
Name: Unnamed: 14, dtype: int64

In [12]:
combined_df.isna().sum()

Created_at        0
LT(M2)            0
LB(M2)            1
KT                6
KM                5
Garasi         1111
Carport         572
Lokasi            0
Sertifikat       11
Listrik         243
Hadap          1749
Harga             2
URL               3
Deskripsi        26
Unnamed: 14    3060
dtype: int64

In [13]:
df = combined_df.drop(['Unnamed: 14', 'URL', 'Deskripsi'], axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3066 entries, 0 to 3065
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Created_at  3066 non-null   object
 1   LT(M2)      3066 non-null   float64
 2   LB(M2)      3065 non-null   float64
 3   KT          3060 non-null   float64
 4   KM          3061 non-null   float64
 5   Garasi      1955 non-null   float64
 6   Carport     2494 non-null   float64
 7   Lokasi      3066 non-null   object
 8   Sertifikat  3055 non-null   object
 9   Listrik     2823 non-null   object
 10  Hadap       1317 non-null   object
 11  Harga       3064 non-null   object
dtypes: float64(6), object(6)
memory usage: 287.6+ KB

In [14]:
df['Created_at'].value_counts()

2023-06-06 00:00:00    366
2023-07-06 00:00:00    330
2021-06-12 00:00:00    248
2021-12-06 00:00:00    231
2021-07-12 00:00:00    149
                      ...
2023-08-06 00:00:00      1
2023-07-28 00:00:00      1
2023-07-08 00:00:00      1
2023-07-14 00:00:00      1
24-07-2023               1
Name: Created_at, Length: 323, dtype: int64

In [15]:
df['Created_at'].value_counts().idxmax()

datetime.datetime(2023, 6, 6, 0, 0)

In [16]:
df["Created_at"].replace(np.nan, "2023-06-06", inplace=True)

In [17]:
df['Sertifikat'].value_counts()

SHM                                2727
SHGB                                121
HGB                                 117
lainnya(PPJB, GIRIK, ADAT, dll)      20
SHM + IMB                            17
Lainnya                              14
PPJB                                 11
SPPJB                                 4
SHM - IMB                             4
HP                                    3
Lainnya (PPJB,Girik,Adat,dll)         3
SHM,IMB                               2
SHM                                   2
PPJB,Girik,Adat,dll                   2
SHM + IMB + PBB                       1
Hak Pakai                             1
AJB                                   1
SHM + Hak Pakai                       1
HJB                                   1
SHM & IMB                             1
SHBG                                  1
SMB                                   1
Name: Sertifikat, dtype: int64

In [18]:
df['Sertifikat'].value_counts().idxmax()

'SHM'

In [19]:
df["Sertifikat"].replace(np.nan, "SHM", inplace=True)

In [20]:
df['Hadap'].value_counts()

Timur                     362
Utara                     301
Selatan                   286
Barat                     166
Timur Laut                 31
selatan                    30
Tenggara                   25
Barat Daya                 23
timur                      22
utara                      19
Barat Laut                 14
barat                       8
utara - barat               3
Timur                       3
timur - selatan             2
tenggara                    2
Utara-Timur                 2
utara - selatan             1
Timur-Utara                 1
Utara-Barat                 1
Selatan dan Timur           1
Utara dan Timur (Hook)      1
selatan - barat             1
Selatan & Barat             1
Timur laut                  1
Barat & Selatan             1
timur utara                 1
barat laut                  1
barat                       1
Selatan dan Utara           1
Selatan dan Barat           1
Danau                       1
Selatan, Utara              1
Timur, Utara                1
Selatan/Timur               1
Name: Hadap, dtype: int64

In [21]:
df['Hadap'].value_counts().idxmax()

'Timur'

In [22]:
df["Hadap"].replace(np.nan, "Timur", inplace=True)

In [23]:
rataLB = df["LB(M2)"].astype("float").mean(axis=0)
print("Rata-Rata LB : ", rataLB)

Rata-Rata LB :  160.47856443719414

In [24]:
df["LB(M2)"].replace(np.nan, rataLB, inplace=True)

In [25]:
rataLT = df["LT(M2)"].astype("float").mean(axis=0)
print("Rata-Rata LT : ", rataLT)

Rata-Rata LT :  190.79528049575998

In [26]:
df["LT(M2)"].replace(np.nan, rataLT, inplace=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3066 entries, 0 to 3065
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Created_at  3066 non-null   object
 1   LT(M2)      3066 non-null   float64
 2   LB(M2)      3066 non-null   float64
 3   KT          3060 non-null   float64
 4   KM          3061 non-null   float64
 5   Garasi      1955 non-null   float64
 6   Carport     2494 non-null   float64
 7   Lokasi      3066 non-null   object
 8   Sertifikat  3066 non-null   object
 9   Listrik     2823 non-null   object
 10  Hadap       3066 non-null   object
 11  Harga       3064 non-null   object
dtypes: float64(6), object(6)
memory usage: 287.6+ KB

In [28]:
df.dropna(subset=["Garasi"], axis=0, inplace=True)

In [29]:
df.dropna(subset=["Carport"], axis=0, inplace=True)

In [30]:
df.dropna(subset=["Listrik"], axis=0, inplace=True)

In [31]:
df.dropna(subset=["Harga"], axis=0, inplace=True)

In [32]:
df.dropna(subset=["KT"], axis=0, inplace=True)

In [33]:
df.dropna(subset=["KM"], axis=0, inplace=True)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1741 entries, 0 to 3065
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Created_at  1741 non-null   object
 1   LT(M2)      1741 non-null   float64
 2   LB(M2)      1741 non-null   float64
 3   KT          1741 non-null   float64
 4   KM          1741 non-null   float64
 5   Garasi      1741 non-null   float64
 6   Carport     1741 non-null   float64
 7   Lokasi      1741 non-null   object
 8   Sertifikat  1741 non-null   object
 9   Listrik     1741 non-null   object
 10  Hadap       1741 non-null   object
 11  Harga       1741 non-null   object
dtypes: float64(6), object(6)
memory usage: 176.8+ KB

In [35]:
df.isna().sum()

Created_at    0
LT(M2)        0
LB(M2)        0
KT            0
KM            0
Garasi        0
Carport       0
Lokasi        0
Sertifikat    0
Listrik       0
Hadap         0
Harga         0
dtype: int64

In [36]:
nama_file_excel = 'DataProperty_Clean.xlsx'
df.to_excel(nama_file_excel, index=False)